# Workflow to verify the code style of the commit, that it builds correctly
# and make sure unit tests run too with all supported node versions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    env:
      PROJECT_CONFIG: ${{ github.workspace }}/examples/config.js
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - name: copy env file
      run: cp .env.example .env
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: yarn
    - name: Compile
      run: yarn compile
    - name: Build Client bundle
      run: yarn build:prod
    - name: Unit Test
      run: yarn test
    - name: UI Test
      run: yarn test:ui
  
  code-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - name: Install
      run: yarn install
    - name: Compile
      run: yarn compile
    - name: Lint
      run: yarn lint

  cargo-test:
    name: Json2capnp
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
      with:
        toolchain: stable
    - run: cargo build
      working-directory: ./services/json2capnp
    - run: cargo test
      working-directory: ./services/json2capnp
